version: 0.2 

phases:
  build:
    commands:
      - python --version || true
      - python2 --version || true
      - python3 --version || true
      - python main.py
  
  post_build:
    commands:
      - if [[ $CODEBUILD_BUILD_SUCCEEDING == 1 ]]; then python3.6 ./scripts/codebuild/rebuild_pull_requests.py; fi
