version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - git log --graph --oneline --all
      - git status
      - git branch
      - git checkout $BRANCH
      - git merge master
      - python main.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.py
