version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - git status
      - git branch
      - git checkout $BRANCH
      - git config user.name 'CodeBuild'
      - git config user.email 'fake@fake.fake'
      - git merge master
      - ls -f
      - ls .. -f
      - ls ../.. -f
      - python main.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.py
