version: 0.2 

phases:
  build:
    commands:
      - python main.py
  
  post_build:
    commands:
      - [[ $CODEBUILD_BUILD_SUCCEEDING == 1 ] && python3.6 ./scripts/codebuild/rebuild_pull_requests.py
