version: 0.2 

phases:
  build:
    commands:
      - "echo MERGE_BRANCH: $MERGE_BRANCH"
      - "git checkout master"
      - "git -c user.name='' -c user.email='' merge $MERGE_BRANCH"
      - "python main.py"
