version: 0.2 

phases:
  build:
    commands:
      - "echo MERGE_BRANCH: $MERGE_BRANCH"
      - "git checkout master"
      - "git -c user.name='CodeBuild' -c user.email='fake@email.org' merge $MERGE_BRANCH"
      - "python main.py"
