version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Merge should happen here
      - git status
      - git branch
      - ls -f
      - ls .. -f
      - ls ../.. -f
      - python main.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.py
