version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Merge should happen here
      - git status
      - git log --oneline
      - python HelloWorld.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.py
